### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by mafar** [jfstephe/cytoscape.js-elk#2]
can u explain how do i use options from http://www.eclipse.org/elk/reference/
I tried setting direction of chart using 
http://www.eclipse.org/elk/reference/options/org-eclipse-elk-direction.html
```js
layout: {
              name: 'elk',
              fit: true,
              elk: {
                direction: 'top',
              },
            }
```
But nothing happens

**Comment by jfstephe** [comment]
All good?

**Comment by mafar** [comment]
Please update doc where it says 
// All options are available at http://www.eclipse.org/elk/reference.html
    // 'org.eclipse.elk.' can be dropped from the Identifier
    // Or look at demo.html for an example.

and write some exampleshere like above for new ones to understand

**Comment by mafar** [comment]
demo is not working as well

**Comment by jfstephe** [comment]
Please raise separate issue for demo.html (I thought it was working), with details.

Is it the specificity of the property name or the casing in the property value that caused you problems?

**Comment by mafar** [comment]
specificity of the property name .. let me write u text wait

**Comment by mafar** [comment]
// All options are available at http://www.eclipse.org/elk/reference/options.html
  // 'org.eclipse.' can be dropped from the Identifier
  //  for example to change layout option as per doc http://www.eclipse.org/elk/reference/options/org-eclipse-elk-algorithm.html
  //  Identifier is  org.eclipse.elk.algorithm , so use { 'elk.algorithm' : 'box'}
  // 
  // Enums use the name of the enum e.g. 'searchOrder': 'DFS'
 //
