### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by cloakedch** [jfstephe/cytoscape.js-elk#6]
After running `npm install cytoscape-elk`, importing it with `import elk from 'cytoscape-elk'` and using it with `cytoscape.use(elk);` I get the following error within node:

**ERROR in ./node_modules/bindings/bindings.js
Module not found: Error: Can't resolve 'fs' in './node_modules/bindings'**

Installing 'fs' (`npm install --save fs`) does not solve the issue.

Any ideas?

node: v10.16.0
npm: 6.9.0

**Comment by cloakedch** [comment]
Fixed it using https://www.amadousall.com/angular-cli-module-not-found-error-cant-resolve/
(I often forget that there are people still using plain javascript).

**Comment by jfstephe** [comment]
Thanks - was just reading this now :-)
